image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.11

stages:
  - test
  - doc
  - publish

pytest-macos:
  stage: test
  tags:
    - catalina-py311-x64
  script:
    - export UV_PYTHON="3.13"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_MACOS_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_macos1.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests/test_logging.py tests
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_macos2.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests/test_logging.py
    - opsi-dev-cli -l info testing merge-junit-testreports testreport_macos1.xml testreport_macos2.xml testreport_macos.xml
    - mv .coverage coverage_macos
  artifacts:
    name: "python-opsi-common_test_macos"
    paths:
      - coverage.xml
      - testreport_macos.xml
      - coverage_macos
    expire_in: 3 days

pytest-windows:
  stage: test
  tags:
    - win10-py311-x86
  script:
    - $Env:UV_PYTHON_INSTALL_DIR = "c:\\uv\\python"
    - $Env:UV_CACHE_DIR = "c:\\uv\\cache"
    - $Env:UV_PYTHON_PREFERENCE = "only-managed"
    - $Env:UV_PYTHON = ((uv python list | findstr 3.13 | findstr "\-x86\-" | findstr /v freethreaded) -split ' ')[0]
    - irm "${OPSIDEVTOOLS_INSTALLER_URL_WINDOWS_X86}" | iex
    - uv sync --frozen
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_windows1.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests\\test_logging.py tests
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_windows2.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests\\test_logging.py
    - opsi-dev-cli -l info testing merge-junit-testreports testreport_windows1.xml testreport_windows2.xml testreport_windows.xml
    - Rename-Item -Path .coverage -NewName coverage_windows
  artifacts:
    name: "python-opsi-common_test_windows"
    paths:
      - coverage.xml
      - testreport_windows.xml
      - coverage_windows
    expire_in: 3 days

pytest-linux:
  stage: test
  script:
    - export UV_PYTHON="3.13"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - apt update
    - apt --yes install zstd # need zstd for packaging tests
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_linux1.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests/test_logging.py tests
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_linux2.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests/test_logging.py
    - opsi-dev-cli -l info testing merge-junit-testreports testreport_linux1.xml testreport_linux2.xml testreport_linux.xml
    - mv .coverage coverage_linux
  artifacts:
    name: "python-opsi-common_test_linux"
    paths:
      - coverage.xml
      - testreport_linux.xml
      - coverage_linux
    expire_in: 3 days

lint-and-test:
  stage: test
  needs:
    # We want to combine test coverage from all test jobs
    - job: pytest-windows
      artifacts: true
    - job: pytest-macos
      artifacts: true
    - job: pytest-linux
      artifacts: true
  script:
    - export UV_PYTHON="3.13"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - apt-get update
    - apt-get --yes --allow-downgrades install libsqlite3-0=3.16.2-5+deb9u1
    - apt-get --yes install sqlite3
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run ruff check opsicommon tests
    - uv run ty check opsicommon tests
    - for db in coverage_*; do sqlite3 $db 'update file set path=replace(substr(path,instr(path,"opsicommon")),"\","/");'; done
    - echo -e '[run]\nrelative_files = True\n' > .coveragerc
    - uv run coverage combine coverage_*
    - uv run coverage xml
    - uv run coverage report
    - opsi-dev-cli -l info testing merge-junit-testreports testreport_*.xml testreport.xml
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    name: "python-opsi-common_test"
    paths:
      - coverage.xml
    expire_in: 3 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: testreport.xml

build-and-publish-apidoc:
  stage: doc
  when: manual
  before_script:
    - "which ssh-agent || (apt update && apt -y install openssh-client)"
    - "which rsync || (apt update && apt -y install rsync)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$BLOG_PUBLISH_PRIVATE_KEY")
  script:
    - export UV_PYTHON="3.13"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli apidoc makehtml --output python-opsi-common
    - ssh -o StrictHostKeyChecking=no "root@docker1.ext.uib.gmbh" "mkdir -p /var/lib/docker/volumes/docs_nginx_data/_data/python-docs"
    - rsync -e "ssh -o StrictHostKeyChecking=no" --delete -azv python-opsi-common "root@docker1.ext.uib.gmbh:/var/lib/docker/volumes/docs_nginx_data/_data/python-docs/"

publish-uib-pypi:
  stage: publish
  script:
    - export UV_PYTHON="3.13"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli -l info pypi publish --url https://pypi.uib.gmbh --overwrite
  only:
    - tags
