image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.9

stages:
  - test
  - publish

test:pytest-darwin:
  #when: manual
  stage: test
  tags:
    - macos
  script:
    # /etc/sudoers
    # runner ALL=(ALL) NOPASSWD: ALL
    - source $HOME/.poetry/env
    - poetry install
    - sudo poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests/test_logging.py tests
    - sudo poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests/test_logging.py
    - mv .coverage coverage_darwin
  after_script:
    - sudo chown -R $USER .
  artifacts:
    name: 'python-opsi-common_test_darwin'
    paths:
      - coverage_darwin.xml
      - testreport_darwin.xml
      - coverage_darwin
    expire_in: 3 days

test:pytest-windows:
  #when: manual
  stage: test
  tags:
    - win10
  script:
    - poetry install
    - poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests\\test_logging.py tests
    - poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests\\test_logging.py
    - Rename-Item -Path .coverage -NewName coverage_windows
  artifacts:
    name: 'python-opsi-common_test_windows'
    paths:
      - coverage_windows.xml
      - testreport_windows.xml
      - coverage_windows
    expire_in: 3 days

test:pytest-linux:
  #when: manual
  stage: test
  script:
    - poetry install
    - poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests/test_logging.py tests
    - poetry run pytest --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests/test_logging.py
    - mv .coverage coverage_linux
  artifacts:
    name: 'python-opsi-common_test_linux'
    paths:
      - coverage_linux.xml
      - testreport_linux.xml
      - coverage_linux
    expire_in: 3 days

test:pylint-pytest:
  #when: manual
  stage: test
  needs:
    # We want to combine test coverage from all test jobs
    - job: test:pytest-windows
      artifacts: true
    - job: test:pytest-darwin
      artifacts: true
    - job: test:pytest-linux
      artifacts: true
  script:
    - apt-get update
    - apt-get --yes install sqlite3
    - poetry install
    - poetry run pylint --disable=R,fixme opsicommon tests
    - poetry run flake8 opsicommon tests
    - for db in coverage_*; do sqlite3 $db 'update file set path=replace(substr(path,instr(path,"opsicommon")),"\","/");'; done
    - echo -e '[run]\nrelative_files = True\n' > .coveragerc
    - poetry run coverage combine coverage_*
    - poetry run coverage xml
    - poetry run coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    name: 'python-opsi-common_test'
    paths:
      - coverage.xml
    expire_in: 3 days
    reports:
      cobertura: coverage.xml
      # TODO: Merge testrepots
      junit: testreport_linux.xml


publish:uibpypi:
  stage: publish
  script:
    - poetry install
    - poetry run opsi-dev-tool -l info --uib-pypi-publish
  only:
    - tags
