image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.9

stages:
  - test
  - publish

test:pylint-pytest:
  #when: manual
  stage: test
  script: |
    poetry install
    poetry run pylint --disable=R,fixme opsicommon
    poetry run pytest -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v --ignore=tests/test_logging.py tests
    poetry run pytest -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsicommon --cov-report term --cov-report xml -v tests/test_logging.py
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    name: 'python-opsi-common_test'
    paths:
      - coverage.xml
      - testreport.xml
    reports:
      junit: testreport.xml
    expire_in: 7 days

publish:uibpypi:
  stage: publish
  script:
    - poetry install
    - poetry run opsi-dev-tool -l info --uib-pypi-publish
  only:
    - tags
