[project]
name = "python-opsi-common"
version = "4.3.54.12"
description = "The opsi python common library"
readme = "README.md"
license = "AGPL-3.0-only"
requires-python = ">=3.11,<3.15"
dependencies = [
	"aiofiles>=24.1",
	"annotated-types>=0.7",
	"blake3>=1.0.8",
	"colorlog>=6.6",
	"cryptography>=42.0",
	"distro>=1.6",
	"dnspython>=2.7.0",
	"lz4>=4.0",
	"mailbits>=0.2",
	"msgpack>=1.0; platform_system == 'Windows'",
	"msgspec>=0.19; platform_system != 'Windows'",
	"netifaces>=0.11.0",
	"packaging>=24.1",
	"psutil>=5.8",
	"ptyprocess>=0.7",
	"pycryptodome>=3.10",
	"pydantic-core>=2.20",
	"pydantic>=2.9",
	"pywin32>=308; platform_system == 'Windows'",
	"pywinpty>=2.0; platform_system == 'Windows'",
	"pyzsync>=1.0",
	"requests>=2.26",
	"rich>=13.8",
	"tomlkit>=0.13",
	"websocket-client>=1.4",
	"wmi>=1.5; platform_system == 'Windows'",
	"zstandard>=0.21",
]

[[project.authors]]
name = "uib GmbH"
email = "info@uib.de"

[[project.maintainers]]
name = "uib GmbH"
email = "info@uib.de"

[project.urls]
Homepage = "https://www.opsi.org"

[dependency-groups]
dev = [
	"hypothesis>=6.111",
	"perflint>=0.7",
	"pproxy>=2.7",
	"pytest-asyncio>=0.24",
	"pytest-cov>=4.0",
	"pytest>=7.0",
	"pyupgrade>=3.0",
	"ruff>=0.6",
	"ty>=0.0.1a34",
	"types-aiofiles>=24.1",
	"types-netifaces>=0.11.0.20241025",
	"types-orjson>=3.6",
	"types-psutil>=6.0",
	"types-requests>=2.32",
]

[tool.uv]
extra-index-url = ["https://pypi.uib.gmbh/simple"]
index-strategy = "unsafe-best-match"
package = true

[tool.ruff]
line-length = 140

[tool.ruff.format]
indent-style = "tab"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.packages.find]
include = ["opsicommon", "opsicommon.*"]
