[tool.poetry]
name = "python-opsi-common"
version = "4.2.0.272"
description = "The opsi python common library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "opsicommon" }
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"
secondary = true

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
colorlog = "^6.6"
distro = "^1.6"
lz4 = "^3.1"
msgpack = "^1.0"
psutil = "^5.8"
pycryptodome = "^3.10"
pyopenssl = "^22.0"
pywin32 = {platform = "win32", version = "^303"}
requests = "^2.26"

[tool.poetry.dev-dependencies]
flake8 = "^4.0"
hypothesis = "^6.32"
opsi-dev-tools = "^1.1"
pylint = "^2.7"
pytest = "^7.0"
pytest-cov = "^3.0"
mypy = "^0.931"
tan = "^21.14"
types-requests = "^2.27"
types-orjson = "^3.6"

[tool.black]
line-length = 140
target-version = ['py39', 'py310']
use-tabs = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
