[tool.poetry]
name = "python-opsi-common"
version = "4.2.0.263"
description = "The opsi python common library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "opsicommon" }
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
colorlog = "^6.6.0"
psutil = "^5.8.0"
pycryptodome = "^3.10.1"
msgpack = "^1.0.2"
requests = "^2.26.0"
lz4 = "^3.1.3"

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.0"
pytest = "^6.2.3"
pytest-cov = "^3.0.0"
pylint = "^2.7.4"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
