[tool.poetry]
name = "python-opsi-common"
version = "4.2.0.269"
description = "The opsi python common library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "opsicommon" }
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
colorlog = "^6.6.0"
distro = "^1.6.0"
lz4 = "^3.1.3"
msgpack = "^1.0.2"
psutil = "^5.8.0"
pycryptodome = "^3.10.1"
pyopenssl = "^21.0.0"
pywin32 = {platform = "win32", version = "^227"}
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
hypothesis = "^6.32.1"
opsi-dev-tools = "^1.1"
pylint = "^2.7.4"
pytest = "^6.2.3"
pytest-cov = "^3.0.0"
mypy = "^0.931"
tan = "^21.14"
types-requests = "^2.27.8"
types-orjson = "^3.6.2"

[tool.black]
line-length = 140
target-version = ['py39', 'py310']
use-tabs = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
