[tool.poetry]
name = "python-opsi-common"
version = "4.3.0.3"
description = "The opsi python common library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "opsicommon" }
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"
secondary = true

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
colorlog = "^6.6"
distro = "^1.6"
lz4 = "^4.0"
msgpack = "^1.0"
msgspec = "^0.12"
orjson = "^3.8"
psutil = "^5.8"
pycryptodome = "^3.10"
pyopenssl = "^23.0"
pywin32 = {platform = "win32", version = "^303"}
requests = "^2.26"
rich = "^13.0"
websocket-client = "^1.4"

[tool.poetry.dev-dependencies]
flake8 = "^6.0"
hypothesis = "^6.32"
pylint = "^2.7"
pytest = "^7.0"
pytest-cov = "^4.0"
mypy = "^0.991"
tan = "^22.2"
types-requests = "^2.27"
types-orjson = "^3.6"
isort = "^5.10.1"
perflint = "^0.7.3"
pyupgrade = "^3.0.0"

[tool.black]
line-length = 140
target-version = ['py39', 'py310']
use-tabs = true

[tool.isort]
profile = "black"
indent = "\t"

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
