[tool.poetry]
name = "python-opsi-common"
version = "4.3.0.38"
description = "The opsi python common library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "opsicommon" }
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"
secondary = true

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
colorlog = "^6.6"
distro = "^1.6"
lz4 = "^4.0"
msgpack = "^1.0"
msgspec = "^0.12"
psutil = "^5.8"
pycryptodome = "^3.10"
pyopenssl = "^23.0"
pywin32 = {platform = "win32", version = ">=303"}
wmi = {platform = "win32", version = "^1.5"}
requests = "^2.26"
rich = "^13.0"
websocket-client = "^1.4"
zstandard = "^0.20.0"

[tool.poetry.group.dev.dependencies]
hypothesis = "^6.32"
isort = "^5.10.1"
mypy = "^0.991"
perflint = "^0.7.3"
pylint = "^2.7"
pytest = "^7.0"
pytest-cov = "^4.0"
pyupgrade = "^3.0.0"
ruff = "^0.0.239"
tan = "^22.2"
types-orjson = "^3.6"
types-requests = "^2.27"

[tool.ruff]
line-length = 140
# As long as pylint is in use:
# Ignore F401 (imported but unused)
# Ignore E402 (Module level import not at top of file)
ignore = ["F401", "E402"]

[tool.black]
line-length = 140
target-version = ['py39', 'py310']
use-tabs = true

[tool.isort]
profile = "black"
indent = "\t"

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
